hydra:
  run:
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Aug10_w_summse_noreqgrad_tmux23/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Aug10_no_summse_noreqgrad_tmux22/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Aug7_NO_summse_tmux21/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Aug27_Wsummse_curr_preds_mask_like_loss_tmux29/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept9_highSoftMSE_Tmux36/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/OCT20_fixes_FullTIMIT_tmux2ironman/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Nov19_fullTIMIT_adaptive_loss_new_phi_calc_logsumexp_tmux7ironman/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec1_fullTIMIT_TRYFASTRUN_tmux4Hulk_gpu4/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec7_BuckeyeOrig_tmux0Thanos_gpu0/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec9_IFAdutchReorder_tmux0Thanos_gpu0/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec15_FullTIMIT_torchfix_tmux6Hulk_gpu6/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec15_IFAdutchReorder_tmux0Thanos_gpu0/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec24_Dutch_tmux7Hulk_gpu7/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec28_TIMIT_NaivePeakDetection_noBiLSTM_tmux7Hulk_gpu7/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/DPnoBiLSTM_tmux2Thanos_gpu0/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec28_TIMIT_regularDPnoBiLSTM_tmux1Thanos_gpu1/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Feb2_TIMIT_InfoNCE_tmux12Hulk_gpu7/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Run_for_projectGitHub_Hulk/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec28_TIMIT_regularDP_tmux0Thanos_gpu0/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec16_TIMITplaygroundProfiled_tmux0Thanos_gpu0/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec9_BuckeyeOrig_tmux0Thanos_gpu0/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec2_BuckeyePreprocessed_frame_labelsNotZeroATlossNotForward_HulkTmux1gpu1/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec2_fullTIMIT_frame_labelsNotZeroATlossNotForward_HulkTmux5gpu5/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Dec1_BuckeyeOrig_tmux4Hulk_gpu4/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Nov30_fullTIMIT_val_on_trainTrue_tmux3Hulk_gpu3/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Nov30_fullTIMIT_lstmfix_zerocrossdriv_tmux2Hulk_gpu2/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Nov26_fullTIMIT_lstmfix_zerocrossdriv_tmux0Hulk_gpu0/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/OCT21_fullTIMIT_adaptive_loss_tmux6ironman/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/OCT21_timitplayground_adaptive_loss/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/OCT21_TIMITplayground_adaptive_loss/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/OCT20_FullTIMITlarge_gamma_tmux5ironman/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/OCT20_FullIFADutch_tmux4ironman/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/OCT20_fixes_BuckeyePlayground_smallMSE/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/OCT20_fixes_FULLBuckeye_smallMSE/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/OCT15_fixes_FULLTIMIT_smallMSE/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/OCT15_fixes/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept16_dp_backtrack_pointer_fixed_Tmux42/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept15_dp_fixes_Tmux41/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept15_ph61_Tmux41/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept14_ph61_Tmux40/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept10_truthprobs_ph61_ZeroPadding_Tmux39/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept9_truthprobs_ph61_ZeroPadding_playground/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept9_truthprobs_ph61_Tmux38/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept9_truthprobs_ph61_Playground/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept9_Buckeye_Tmux38/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/BuckeyeTRY/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept8_thruthpreds_withPHLOSS_lowerlr_tmux37/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept8_Sameastmux34_lowerlr_tmux36/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept3_both_preds_and_derivative_w_phi123_tmux34/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept3_both_preds_and_derivative_nologphi2_tmux30/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept3_both_preds_and_derivative_wphloss_tmux31/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept2_both_preds_and_derivative_Buckeye_tmux33/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept2_no_derivative_tmux31/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Sept2_loss_as_peaks_tmux30/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Aug27_loss_as_peaks_TRY/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Aug27_Wsummse_lowWneg_tmux28/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Aug13_Wsummse_large_TMUX26/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Aug11_nosummse_TMUX24/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Aug4_low_summse_tmux5_wanda/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Aug4_low_summse_tmux19/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Aug3_low_summse_tmux18/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/Aug3_no_summse_tmux17/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/July29_fulltimit_tmux15/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/JULY_29_IFA_DUTCH_Tmux9/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/JULY_27_FULLTIMIT_Tmux14/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/JULY_22_wandbFULL_BuckeyeFULL_tmux7/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/JULY_22_wandbFULL_timitFULL_tmux12/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/JULY_15_wandbFULL_timitFULL_TMUX11/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/JULY_14_soft_Align_IFA_dutch_TMUX9/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/JULY_12_soft_Align_fulltimit_TMUX5/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/JULY_05_weighted_soft_Align_timitPlayground_TMUX41/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/JULY_02_with_soft_Align_fulltimit_tmux43/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/JULY_01_fulltimitTmux42/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    
    
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/JULY_2_timitPlaygroundtmux41/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/JUNE_10_fulltimittmux41/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/JUNE_4_timitPlayground/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF2/DCAF2.0/runs/MAY_27_fulltimit_tmux40/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF/runs/MAY_8_train_IFA_DUTCH_tmux38/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF/runs/April_16_TIMIT_tmux27/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF/runs/April_7_TIMIT_tmux25/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF/runs/April1TIMIT_tmux27_newconf_valLossMin/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF/runs/31MarchTIMITplayground_2epochs_tmux26_newconf/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF/runs/DCAF_Hulk31MarchTIMIT_tmux25_newconf/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/DCAF/runs/DCAF_Hulk31MarchTIMITplaygrounds_tmux26_newconf/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/changed_NFC_negative_not_random/runs/DP_AFTERDEBUG_tmux4IronmanTRY_best_l1dist_val0.9_13MARCH/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/changed_NFC_negative_not_random/runs/DP_with_tqdm_tmux15_FEB25/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/changed_NFC_negative_not_random/runs/try_after_git_probs_FEB25_nocpu/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/changed_NFC_negative_not_random/runs/Sample_len_2_FULL_TIMIT_20iter1gpu/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/rotem/projects/CFA/changed_NFC_negative_not_random/runs/Sample_len_2_FULL_TIMIT_5iter/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/mlspeech/rotem/projects/CFA/changed_NFC_negative_not_random/runs/Sample_len_2_FULL_TIMIT/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/mlspeech/rotem/projects/CFA/changed_NFC_negative_not_random/runs/Solver_fixed_full_timit/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/mlspeech/rotem/projects/CFA/changed_NFC_negative_not_random/runs/random_pos_overfit/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/mlspeech/rotem/projects/CFA/changed_NFC_negative_not_random/runs/pos_neg_loss_overfit/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/mlspeech/rotem/projects/CFA/changed_NFC_negative_not_random/runs/pos_neg_loss_FULL_TIMIT_OCT18/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/mlspeech/rotem/projects/CFA/changed_NFC_negative_not_random/runs/try_overfit/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # /home/mlspeech/rotem/projects/CFA/changed_NFC_negative_not_random/runs/half_try_tmux/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # /home/mlspeech/rotem/projects/CFA/changed_NFC_negative_not_random/runs/unsupervised_segmentor/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
    # dir: /home/mlspeech/rotem/projects/CFA/try_felix/runs/unsupervised_segmentor/${now:%Y-%m-%d_%H-%M-%S}-${exp_name}
        #TODO change dir to current file instead of try felix this is where the ckpts are saved
# DATA
libri_path: /data/felix/datasets/librispeech
# buckeye_path: /home/rotem/projects/datasets/buckeye_playground/

# buckeye_path: /home/rotem/projects/datasets/IFA_dutch_reorder

# buckeye_path: /home/rotem/projects/datasets/buckeye_preprocessed/
buckeye_path: /home/rotem/projects/datasets/buckeye/
# buckeye_path: /home/rotem/projects/datasets/IFA_dutch_reorder
# buckeye_path: /home/rotem/projects/datasets/buckeye_playground


# ---------------------- July 14 ----------------------
# buckeye_path: /home/rotem/projects/datasets/IFA_dutch_reorder

# /home/rotem/projects/datasets/buckeye #/data/felix/datasets/buckeye_processed_by_speaker_balanced
timit_path: /home/rotem/projects/datasets/timit/playground


# timit_path: /home/rotem/projects/datasets/timit/timit_tixed
# --------------!!!! MAY 8 !!!! ------------
# --------------!!!! MAY 11 !!!! ------------
# timit_path: /home/rotem/projects/datasets/IFA_dutch_reorder/
# timit_path: /home/rotem/projects/datasets/timit/timit_tixed/


# timit_path: /home/rotem/projects/datasets/buckeye_preprocessed/ 
# timit_path: /home/rotem/projects/datasets/IFA_dutch_reorder

# timit_path: /home/rotem/projects/datasets/IFA_dutch_split/
# timit_path: /home/rotem/projects/datasets/timit_playground_fixed/

# timit_path: /home/rotem/projects/datasets/timit/timit_tixed/


# timit_path: /home/rotem/projects/CFA/changed_NFC_negative_not_random/overfit_check_data_timit
# timit_path: /home/rotem/projects/SelfSupSegFA/SegFA_Rotem/datasets_SegFA/timit
# timit_path: /home/rotem/projects/SelfSupSegFA/SegFA_Rotem/datasets_SegFA/timit_playground
# timit_path: /home/rotem/projects/datasets/timit_playground_fixed
# timit_path: /home/rotem/projects/SelfSupSegFA/SegFA_Rotem/datasets_SegFA/timit


# /home/mlspeech/rotem/projects/SelfSupSegFA/SegFA_Rotem/datasets_SegFA/timit_fixed
#/data/felix/datasets/timit
libri_subset: train-clean-100
libri_percent: 1.0
buckeye_percent: 1.0
val_ratio: 0.1 #0.05 #0.1 #0.001 #0.1 #0.0001 #0.1  # ratio of validation set #need to check if it really reads from this config
val_count: None #2 # None
data: timit #buckeye #timit #buckeye #timit # buckeye #timit #buckeye #timit #timit #buckeye #timit #buckeye #timit #buckeye #timit #buckeye #timit
dataloader_n_workers: 10 #4 #2 #4 #10

# MODEL
cosine_coef: 1.0  # cosine similarity coefficient
z_proj: 64  # size of projection
z_proj_linear: true #false #true
z_proj_dropout: 0 #0.1 #0
z_dim: 256
pred_steps: 1  # number of future prediction steps
pred_offset: 0  # offset of future prediction steps
batch_shuffle: false  # if 'false' negative samples will be from the same utterance, if 'true' may be from different utterances
latent_dim: 0  # latent dimension of encoder
n_negatives: 1  # number of negative samples for contrastive loss

# MISC
gpus: 1 #8 #4 #5 #4 #8 
devices: [7] #[7] #[0] #[1] #[5] #[4] #[0] #[7] #[0,1,2,3,4,5,6,7] #[3,4,6,7] #[0] #[3]  #[1] #[2] # [1] #[2] #[3]
tag: default
exp_name: default
project: unsupervised_segmentor
ckpt: null
dev_run: false  # fast debug run
val_check_interval: 1.0 #0.1 #0.9 #0.003 #0.2 #1 # 0.9 #0.2 #0.9 #0.2  # how often a validation epoch is run
# overfit_pct: 1
seed: 100
early_stop_metric: val_nfc_loss #train_nfc_loss #val_min_l1_dist #val_nfc_loss #val_min_l1_dist #val_nfc_loss #val_min_l1_dist #val_max_rval #val_nfc_loss #val_nfc_loss # val_nfc_loss
early_stop_mode: min #max #min 

# OPTIMIZATION
optimizer: adamW
momentum: 0.9
lr:  3e-4 #0.000714 #0.00005 #0.002 # 0.000714 #1e-5 #0.002 #0.0005 #0.000714 #TMUX 20 -0.000714 #0.001 #TMUX21 - 0.002 #0.0002
# lr:  5e-5 #0.000714 #0.00005 #0.002 # 0.000714 #1e-5 #0.002 #0.0005 #0.000714 #TMUX 20 -0.000714 #0.001 #TMUX21 - 0.002 #0.0002
lr_anneal_gamma: 0.95 #1.0
lr_anneal_step: 1000
epochs: 200 #50 #30 #50 #100 #50 #200 #50 #100 #200
grad_clip: 0.5
batch_size: 8 #1 #8

# ------- December 21 --------
num_classes: 39 #41 #39 #61 #62 #61 #41 #39 #61 #maybe 39? # number of phoneme labels for classification